displayName=Vorky Trainer
author=MrSquidly
description=A plugin to help players learn the mechanics of the Vorkath fight. Currently only support melee attack style.
tags=Vorkath, PvM, Bossing, Learning
plugins=com.vorkytrainer.VorkyTrainerPlugin